server:
  port: 8761


eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry : false


#server:
#  port: 8761 # Port for the Eureka server
#
#eureka:
#  client:
#    register-with-eureka: false # This is the Eureka server, so it won't register itself
#    fetch-registry: false # This is the Eureka server, so it doesn't need to fetch the registry
#  instance:
#    hostname: localhost
